version: '3'

services:
  frontend:
    build: ./
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./:/app/frontend
    entrypoint:
      - npm
      - start
